---

- name: Echo
  hosts: "{{host}}"
  tasks:
  - name: ansible create directory example
    file:
      path: /tmp/%Budrikaite%/java_dns
      state: directory
  - name: download sources
    get_url: url=https://repo1.maven.org/maven2/dnsjava/dnsjava/3.5.0/dnsjava-3.5.0.jar dest=/tmp/%Budrikaite%/java_dns
